name: smartlist
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
 
environment:
  sdk: '>=2.19.3 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.2
  amplify_flutter: ^0.6.14
  amplify_auth_cognito: ^0.6.0
  pytorch_mobile: ^0.2.2
  amazon_cognito_identity_dart_2: ^3.3.0
  amplify_datastore: ^0.6.13
  amplify_api: ^0.6.13
  graphql: ^5.1.3
  syncfusion_flutter_charts: ^21.2.3
  connectivity_plus: ^4.0.0
  provider: ^6.0.5
  pin_input_text_field: ^4.5.1
  pin_code_fields: ^8.0.1
  intl_phone_number_input: ^0.7.3+1
  country_picker: ^2.0.21
  country_code_picker: ^3.0.0
  country_picker_dialog: ^0.0.3
  http: ^0.13.3
  aws_xray_api: ^2.0.0
  shared_preferences: ^2.0.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
  uses-material-design: true
 
  assets:
    - assets/images/
 
    - assets/images/Fruitsvegetables.jpg
    - assets/images/Beverages.jpg
    - assets/images/Bakery.jpg
    - assets/images/Personacare.jpg
    - assets/labels/
    - assets/images/Category.png